# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHb7X_ta5VnpTplvrumxXM7iUygV3x-e
"""

import base64
import os

import streamlit as st

st.set_page_config(page_title="My AI Assistant", page_icon="🤖", layout="wide")


COT_SYSTEM_PROMPT = (
    "Think through this step by step before answering. Put your "
    "reasoning inside <think></think> tags, then give your final "
    "answer after the closing tag."
)

GEMINI_MODEL_HELP = "e.g. gemini-3.6-flash (default), gemini-3.1-pro (harder problems), gemini-3.5-flash-lite (cheap/fast)"



with st.sidebar:
    st.header("Settings")

    provider = st.radio("Backend", ["Gemini (cloud)", "Ollama (local)"], index=0)

    if provider == "Gemini (cloud)":
        model = st.text_input("Model name", value="gemini-3.6-flash", key="gemini_model", help=GEMINI_MODEL_HELP)
        env_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
        if env_key:
            gemini_key = env_key
            st.caption("Using the GEMINI_API_KEY found in your environment.")
        else:
            gemini_key = st.text_input(
                "Gemini API key",
                type="password",
                help="Get one at https://aistudio.google.com/apikey. Not saved anywhere -- only kept for this session.",
            )
    else:
        model = st.text_input("Model name", value="gemma3", key="ollama_model", help=OLLAMA_MODEL_HELP)
        gemini_key = None

    cot_mode = st.toggle(
        "Show step-by-step reasoning (CoT)",
        value=True,
        help="Asks the model to think out loud before giving its final answer.",
    )
    st.divider()

    if provider == "Ollama (local)":
        st.caption(
            "Make sure Ollama is running in the background "
            "(it usually starts automatically after install, or run 'ollama serve')."
        )
    else:
        st.caption("Using Google's Gemini API -- your messages are sent to Google's servers.")

    if st.button("Clear conversation"):
        st.session_state.messages = []
        st.rerun()

st.title("🤖 My AI Assistant")
if provider == "Ollama (local)":
    st.caption("Runs entirely on your own computer through Ollama -- nothing leaves your machine.")
else:
    st.caption("Answered by Google's Gemini API.")

# ---------- Chat history ----------
if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        if msg.get("thinking"):
            with st.expander("💭 Reasoning"):
                st.write(msg["thinking"])
        st.write(msg["content"])

# ---------- Image upload (needs a vision-capable model on either backend) ----------
uploaded_image = st.file_uploader(
    "Attach an image (optional -- needs a vision-capable model)",
    type=["png", "jpg", "jpeg"],
)

# ---------- Handle new input ----------
prompt = st.chat_input("Ask me anything...")

if prompt:
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.write(prompt)
        if uploaded_image is not None:
            st.image(uploaded_image, width=200)

    # ---------- Call the model and stream the reply ----------
    with st.chat_message("assistant"):
        placeholder = st.empty()
        full_text, answer, thinking = "", "", ""

        try:
            if provider == "Ollama (local)":
                try:
                    import ollama
                except ImportError:
                    st.error("The 'ollama' package isn't installed. Run: pip install ollama")
                    st.stop()

                # Build the message list to send to Ollama
                api_messages = []
                if cot_mode:
                    api_messages.append({"role": "system", "content": COT_SYSTEM_PROMPT})
                api_messages.extend(
                    {"role": m["role"], "content": m["content"]} for m in st.session_state.messages
                )
                if uploaded_image is not None:
                    api_messages[-1]["images"] = [uploaded_image.getvalue()]

                stream = ollama.chat(model=model, messages=api_messages, stream=True)
                for chunk in stream:
                    full_text += chunk["message"]["content"]

                    if "<think>" in full_text:
                        thinking = full_text.split("<think>", 1)[1].split("</think>")[0]
                    if "</think>" in full_text:
                        answer = full_text.split("</think>", 1)[1]
                    elif "<think>" not in full_text:
                        answer = full_text

                    with placeholder.container():
                        if thinking:
                            with st.expander("💭 Reasoning", expanded=not answer):
                                st.write(thinking)
                        st.write(answer)

            else:  # Gemini (cloud)
                if not gemini_key:
                    st.error("Enter a Gemini API key in the sidebar (or set GEMINI_API_KEY) to use this backend.")
                    st.stop()

                from google import genai
                from google.genai import types

                client = genai.Client(api_key=gemini_key)

                # Same idea as the Ollama branch: "assistant" -> "model", plain
                # text turns for history. Gemini takes the CoT instruction as a
                # system_instruction rather than a message in the list.
                contents = [
                    types.Content(
                        role=("model" if m["role"] == "assistant" else "user"),
                        parts=[types.Part.from_text(text=m["content"])],
                    )
                    for m in st.session_state.messages
                ]
                if uploaded_image is not None:
                    contents[-1].parts.append(
                        types.Part.from_bytes(
                            data=uploaded_image.getvalue(),
                            mime_type=uploaded_image.type or "image/png",
                        )
                    )

                config = types.GenerateContentConfig(
                    system_instruction=COT_SYSTEM_PROMPT if cot_mode else None,
                )
                stream = client.models.generate_content_stream(model=model, contents=contents, config=config)
                for chunk in stream:
                    full_text += chunk.text or ""

                    if "<think>" in full_text:
                        thinking = full_text.split("<think>", 1)[1].split("</think>")[0]
                    if "</think>" in full_text:
                        answer = full_text.split("</think>", 1)[1]
                    elif "<think>" not in full_text:
                        answer = full_text

                    with placeholder.container():
                        if thinking:
                            with st.expander("💭 Reasoning", expanded=not answer):
                                st.write(thinking)
                        st.write(answer)

        except Exception as e:
            if provider == "Ollama (local)":
                st.error(
                    f"Couldn't reach Ollama -- make sure it's running and that "
                    f"'{model}' has been pulled. ({e})"
                )
            else:
                st.error(f"Gemini request failed -- check your API key and model name. ({e})")

    st.session_state.messages.append({
        "role": "assistant",
        "content": answer,
        "thinking": thinking or None,
    })

from google import genai

client = genai.Client(api_key="AQ.Ab8RN6I3UFYV-uQHFLssLrO-mwJc7EXcqhS1TQFvnirkLtxung")

for m in client.models.list():
    print(m.name, "-", m.supported_actions)