"""
run_all.py

Runs all four workstreams in order and writes results/REPORT.md, a
one-page summary pulling the headline numbers out of results/summary.json.
This is the single command a reviewer (or you, before an interview) should
run to regenerate everything from scratch.
"""

import subprocess
import sys
import os
import json

ROOT = os.path.dirname(__file__)
RESULTS_DIR = os.path.join(ROOT, "results")

SCRIPTS = [
    ("Workstream 1: Interpretability", "workstream1_interpretability/probe_and_patch.py"),
    ("Workstream 2: Red Team", "workstream2_redteam/attack_loop.py"),
    ("Workstream 3: Systems", "workstream3_systems/benchmark.py"),
    ("Workstream 4: RL Alignment", "workstream4_rl/rlhf_loop.py"),
]


def run_all():
    # fresh summary each full run
    summary_path = os.path.join(RESULTS_DIR, "summary.json")
    if os.path.exists(summary_path):
        os.remove(summary_path)

    for label, script in SCRIPTS:
        print(f"\n{'#' * 70}\n# RUNNING: {label}\n{'#' * 70}")
        result = subprocess.run([sys.executable, script], cwd=ROOT)
        if result.returncode != 0:
            print(f"\n!! {label} failed (exit code {result.returncode}). Stopping.")
            sys.exit(1)

    write_report()


def write_report():
    with open(os.path.join(RESULTS_DIR, "summary.json")) as f:
        s = json.load(f)

    ws1, ws2, ws3, ws4 = (s.get(f"workstream{i}_{name}", {}) for i, name in
                           [(1, "interpretability"), (2, "redteam"), (3, "systems"), (4, "rl")])

    lines = ["# Results report\n", "Auto-generated by `run_all.py`. See `results/*.png` for plots.\n"]

    lines.append("## Workstream 1 -- Interpretability")
    lines.append(f"- Probe accuracy (training concepts): **{ws1.get('probe_accuracy_train_concepts', 0):.3f}**")
    lines.append(f"- Probe accuracy (held-out concepts): **{ws1.get('probe_accuracy_heldout_concepts', 0):.3f}** "
                  "(expected to be weak -- see README caveat on random concept embeddings)")
    base_svr = ws1.get("baseline_iid", {}).get("safety_violation_rate", 0)
    patched_fpr = ws1.get("patched", {}).get("false_positive_rate", 0)
    lines.append(f"- Ablating the probe direction pushes false positive rate to "
                 f"**{patched_fpr:.3f}** (from baseline) -- the safety behavior collapses when "
                 f"the direction is removed.")
    lines.append(f"- SAE dead feature fraction: **{ws1.get('sae_dead_feature_frac', 0):.1%}**\n")

    lines.append("## Workstream 2 -- Red Team (real PGD)")
    lines.append(f"- Attack Success Rate before defense: **{ws2.get('asr_before_defense', 0):.1%}**")
    lines.append(f"- Attack Success Rate after adversarial fine-tuning: **{ws2.get('asr_after_defense', 0):.1%}**")
    fpr_after = ws2.get("defended_metrics", {}).get("false_positive_rate", 0)
    lines.append(f"- False positive rate after defense: **{fpr_after:.1%}** "
                  "(the usability cost of that ASR reduction)\n")

    lines.append("## Workstream 3 -- Systems")
    results = ws3.get("results", [])
    for r in results:
        if r.get("batch_size") == 256 and "overhead_pct_vs_base" in r:
            lines.append(f"- {r['name']}: **+{r['overhead_pct_vs_base']:.1f}%** latency vs. base "
                          f"(batch=256, P50={r['p50_ms']:.3f}ms)")
    lines.append("")

    lines.append("## Workstream 4 -- RL Alignment / reward-hacking audit")
    pre, post = ws4.get("pre", {}), ws4.get("post", {})
    lines.append(f"- Safety violation rate: {pre.get('violation_rate', 0):.3f} -> "
                  f"**{post.get('violation_rate', 0):.3f}**")
    lines.append(f"- Output diversity change: **{ws4.get('diversity_drop_pct', 0):+.1f}%**")
    lines.append(f"- Unsafe-direction projection: {pre.get('unsafe_proj', 0):.3f} -> "
                  f"**{post.get('unsafe_proj', 0):.3f}**")
    verdict = "REWARD HACKING DETECTED" if ws4.get("reward_hacking_detected") else "genuine suppression"
    lines.append(f"- **Verdict: {verdict}**\n")

    report_path = os.path.join(RESULTS_DIR, "REPORT.md")
    with open(report_path, "w") as f:
        f.write("\n".join(lines))
    print(f"\n[wrote {os.path.relpath(report_path)}]")


if __name__ == "__main__":
    os.makedirs(RESULTS_DIR, exist_ok=True)
    run_all()
